/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ShareCoin__factory } from "./ShareCoin__factory";
export { ShareCoinStaking__factory } from "./ShareCoinStaking__factory";
